palette:
  top: '#8e0514'
  bottom: '#c3241d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#590003'
logo: 'public://color/bartik-0f7efe99/logo.svg'
stylesheets:
  - 'public://color/bartik-0f7efe99/colors.css'
files:
  - 'public://color/bartik-0f7efe99/logo.svg'
  - 'public://color/bartik-0f7efe99/colors.css'
