palette:
  top: '#8e8905'
  bottom: '#c3c21d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#595600'
logo: 'public://color/bartik-b6d11a9d/logo.svg'
stylesheets:
  - 'public://color/bartik-b6d11a9d/colors.css'
files:
  - 'public://color/bartik-b6d11a9d/logo.svg'
  - 'public://color/bartik-b6d11a9d/colors.css'
